### ISSUE TITLE
connection to build.wireguard.com:443 failed when build kernel

### ISSUE THREAD

**Issue by ihexon** [nathanchance/marlin#1]
In `"scripts/fetch-latest-wireguard.sh"`
```bash
while read -r distro package version _; do
	if [[ $distro == upstream && $package == kmodtools ]]; then
		VERSION="$version"
		break
	fi
done < <(curl -A "$USER_AGENT" -LSs https://build.wireguard.com/distros.txt)
```
but `https://build.wireguard.com/distros.txt` seems to be close down now.....
so when i build kernel, it always report error:

"`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to build.wireguard.com:443`"

**Comment by nathanchance** [comment]
You can revert WireGuard for the time being or wait until the list is back up upstream.

62a0024e887d7b06aec23997b477efe0db8b2c59
4402857c96c7fe245a047075aac9f8aafccac792
4e4a52719ddf6c28229cf19a666aa3d7f0f7238c
